version: '3'

services:
  frontend:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://backend:8080
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./web:/app 
      - /app/node_modules
      - ./web/src/styles:/app/src/styles
    depends_on:
      - backend
    networks:
      - louie_shared_network

  backend:
    container_name: service
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development  
    volumes:
      - ./service:/app  
    networks:
      - louie_shared_network
    secrets:
      - db_url

  unit-tests:
    container_name: unit-tests
    build:
      context: ./unit-tests
      dockerfile: Dockerfile
    volumes:
      - ./unit-tests:/app
      - ./service:/app/service
    networks:
      - louie_shared_network
    depends_on:
      - frontend
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  acceptance-tests:
    container_name: acceptance-tests
    build:
      context: ./acceptance-tests
      dockerfile: Dockerfile
    volumes:
      - ./acceptance-tests:/app
    networks:
      - louie_shared_network
    depends_on:
      - frontend
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  louie_shared_network:
    external: true
  
secrets:
  db_url:
    file: ./db_url.txt