version: '3'

services:
  frontend:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://backend:8080
    volumes:
      - ./web:/app 
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - louie_shared_network

  backend:
    container_name: service
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development  
    volumes:
      - ./service:/app  
    depends_on:
      - db
    networks:
      - louie_shared_network

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - louie_shared_network

volumes:
  db-data:

networks:
  louie_shared_network:
    external: true