version: '3.8'

services:
  httpd-proxy-local:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: ./vhosts.conf
    image: proxy-local:1.0
    container_name: proxy-local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/webroot:/usr/local/apache2/htdocs:rw
    networks:
      - louie_shared_network

networks:
  louie_shared_network:
    external: true